### ISSUE TITLE
Update documentation how to run Web Modeler Self-Managed on Amazon Aurora

### ISSUE THREAD

**Issue by christian-konrad** [camunda/camunda-platform-docs#2238] opened 2023-06-13 20:58 UTC
We should update the [documentation on how to connect to Amazon Aurora Postgres](https://docs.camunda.io/docs/next/self-managed/modeler/web-modeler/configuration/database/#running-web-modeler-on-amazon-aurora-postgresql) to reflect the findings and steps described in [this customer support issue](https://jira.camunda.com/browse/SUPPORT-16056?focusedId=289475&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel) so we can refer to that in future, similar issues.

**Comment by jfriedenstab** [comment] 2023-07-03 06:05
@wollefitz I think this was covered with the new troubleshooting guide, right?

**Comment by wollefitz** [comment] 2023-07-03 06:42
Yes, this is a duplicate of https://github.com/camunda/web-modeler/issues/3874

**Closed by wollefitz** 2023-07-03 06:42 UTC
Labels: kind/enhancement, component:modeler, component:self-managed
